### ISSUE TITLE
Errore Database

### ISSUE THREAD

**Issue by Gdvhev** [veluca93/oii-web#26]
Ogni volta che provo ad installare il cms(anche su server diversi) appena lanciato il build e l'install cerco di eseguire qualsiasi comando(ad esempio cmsDropDB) e per ognuno ottengo questo errore:

_adminuser@ubuntu-55:~/oii-web-master/oii-web-master$ cmsDropDB
2014/05/14 14:24:13 - INFO [None] Using configuration file /usr/local/etc/cms.conf.
Traceback (most recent call last):
  File "/usr/local/bin/cmsDropDB", line 5, in <module>
    pkg_resources.run_script('cms==1.1.0pre', 'cmsDropDB')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/EGG-INFO/scripts/cmsDropDB", line 41, in <module>
    from cms.db import drop_db
  File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/db/**init**.py", line 116, in <module>
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2861, in configure_mappers
    mapper._post_configure_properties()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1166, in _post_configure_properties
    prop.init()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/interfaces.py", line 128, in init
    self.do_init()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/properties.py", line 914, in do_init
    self._determine_joins()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/properties.py", line 1051, in _determine_joins
    % self)
sqlalchemy.exc.ArgumentError: Could not determine join condition between parent/child tables on relationship Talk.sender.  Specify a 'primaryjoin' expression.  If 'secondary' is present, 'secondaryjoin' is needed as well._

Sono giorni che cerco un rimedio e non ho trovato nessuno con il mio stesso problema, idee?

**Comment by wil93** [comment]
Riprova con https://github.com/algorithm-ninja/cmsocial che è la versione che usiamo adesso, in caso riapri una issue lì :wink:
